/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BtnAcction;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author DELL
 */
public class acctionBtnDelete extends javax.swing.JPanel {

    /**
     * Creates new form acctionBtnDelete
     */
    
    public acctionBtnDelete() {
        initComponents();
    }

   public void initEvent(BtnAcctionEvent event,int row){
       cmdDELETE.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               event.onDelete(row);
           }
       });
       
       cmdEDIT.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               event.onEdit(row);
           }
       });
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdDELETE1 = new javax.swing.JButton();
        cmdDELETE = new javax.swing.JButton();
        cmdEDIT = new javax.swing.JButton();

        cmdDELETE1.setText("Xoá");
        cmdDELETE1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdDELETE1.setContentAreaFilled(false);
        cmdDELETE1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cmdDELETE.setBackground(new java.awt.Color(255, 0, 0));
        cmdDELETE.setForeground(new java.awt.Color(255, 51, 51));
        cmdDELETE.setText("Xoá");
        cmdDELETE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdDELETE.setContentAreaFilled(false);
        cmdDELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cmdEDIT.setBackground(new java.awt.Color(0, 153, 153));
        cmdEDIT.setForeground(new java.awt.Color(0, 204, 204));
        cmdEDIT.setText("Sửa");
        cmdEDIT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdEDIT.setContentAreaFilled(false);
        cmdEDIT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmdEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEDITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdEDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdDELETE)
                    .addComponent(cmdEDIT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEDITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdEDITActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDELETE;
    private javax.swing.JButton cmdDELETE1;
    private javax.swing.JButton cmdEDIT;
    // End of variables declaration//GEN-END:variables
}
