/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MultipleChoiceCode;

import BtnAcction.AcctionCell;
import BtnAcction.BtnAcctionEvent;
import BtnAcction.BtnCellEditor;
import CauHoi.LoadQuestions;
import CauHoi.Questions;
import com.mysql.cj.protocol.Resultset;
import java.awt.Choice;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DELL
 */
public class jcauhoi extends javax.swing.JFrame {

    private final int GV_ID;
    private final String GV_Ten;
    jcauhoi j = this;

    /**
     * Creates new form jcauhoi
     *
     * @param getID
     * @param getTen
     */
    public jcauhoi(int getID, String getTen) {
        initComponents();
        Cauhoi.setSelected(rootPaneCheckingEnabled);
        GV_ID = getID;
        GV_Ten = getTen;
        tillte.setText("Chào " + GV_Ten);
        this.setLocationRelativeTo(null);
        BtnAcctionEvent event = new BtnAcctionEvent() {
            @Override
            public void onDelete(int row) {
                int macauhoi = (int) jtable_Cauhoi.getValueAt(row, 0);

                int option = JOptionPane.showConfirmDialog(
                        new Home(),
                        "Bạn có muốn xoá câu hỏi ",
                        "Xoá câu hỏi " + macauhoi,
                        JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_NO_OPTION) {
                    String deleteCauhoi = "DELETE FROM cau_hoi WHERE `cau_hoi`.`CH_Id` = ?;";
                    PreparedStatement stmdelete;
                    try {
                        stmdelete = MySQLConnect.MySQLConnect().prepareStatement(deleteCauhoi);
                        stmdelete.setInt(1, macauhoi);
                        boolean a = stmdelete.execute();
                        if (jtable_Cauhoi.isEditing()) {
                            jtable_Cauhoi.getCellEditor().stopCellEditing();
                        }
                        DefaultTableModel model = (DefaultTableModel) jtable_Cauhoi.getModel();
                        model.removeRow(row);
                    } catch (SQLException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

            @Override
            public void onEdit(int row) {
                int CH_Id = (int) jtable_Cauhoi.getValueAt(row, 0);
                String cauhoi = (String) jtable_Cauhoi.getValueAt(row, 2);
                String A = (String) jtable_Cauhoi.getValueAt(row, 3);
                String B = (String) jtable_Cauhoi.getValueAt(row, 4);
                String C = (String) jtable_Cauhoi.getValueAt(row, 5);
                String D = (String) jtable_Cauhoi.getValueAt(row, 6);
                String dapandung = (String) jtable_Cauhoi.getValueAt(row, 7);
                String mucdo = (String) jtable_Cauhoi.getValueAt(row, 8);
                EditCauHoi ech = new EditCauHoi(cauhoi, A, B, C, D, dapandung, mucdo, CH_Id, GV_ID, GV_Ten);
                ech.setVisible(true);
                ech.pack();
                ech.setLocationRelativeTo(null);
                ech.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                j.dispose();
            }
        };
        jtable_Cauhoi.getColumnModel()
                .getColumn(9).setCellRenderer(new AcctionCell());
        jtable_Cauhoi.getColumnModel()
                .getColumn(9).setCellEditor(new BtnCellEditor(event));

        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jtable_Cauhoi.getModel());
        jtable_Cauhoi.setRowSorter(sorter);
        sorter.setSortable(0, false); // disable sorting for column 0
        sorter.toggleSortOrder(1); // sort by column 1

        showCauhoi();
        showChoiceHocPhan(choice_mahocphan, true);
        showDoKho();
        showItem();
        input_id.setText(String.valueOf(maxCH_IDMYSQL()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void showItem() {
        String ItemMucDo = "SELECT MD_Loai FROM muc_do;";
        PreparedStatement stmDapAn;
        PreparedStatement stmMucDo;
        showChoiceHocPhan(HocPhan, false);
        try {

            Dapandung.addItem("A");
            Dapandung.addItem("B");
            Dapandung.addItem("C");
            Dapandung.addItem("D");

            stmMucDo = MySQLConnect.MySQLConnect().prepareStatement(ItemMucDo);
            ResultSet rsMucDo = stmMucDo.executeQuery();
            while (rsMucDo.next()) {
                MucDo.addItem(rsMucDo.getString("MD_Loai"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(EditCauHoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void showChoiceHocPhan(Choice a, boolean all) {
        if (all) {
            a.add("Học Phần(Tất cả)");
        }
        String timkiem = "SELECT * FROM `hoc_phan` WHERE GV_Id = ?;";
        try {
            PreparedStatement stm = MySQLConnect.MySQLConnect().prepareStatement(timkiem);
            stm.setInt(1, GV_ID);
            ResultSet rs = stm.executeQuery();
            while (rs.next()) {
                a.add(rs.getString("HP_Id"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(jcauhoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void showDoKho() {
        choice_dokho.addItem("Độ Khó(Tất cả)");
        choice_dokho.addItem("De");
        choice_dokho.addItem("Trung Binh");
        choice_dokho.addItem("Kho");
    }

    public void showCauhoi() {
        int i = 1;
        LoadQuestions loadQ = new LoadQuestions(GV_ID);
        ArrayList<Questions> listQ = new ArrayList<>();
        listQ = loadQ.loadQuestions(GV_ID);
        String dapanChar = null;
        for (Questions q : listQ) {
            if (q.getDA_DapAnDung().equals(q.getCH_DapAn1())) {
                dapanChar = "A";
            } else if (q.getDA_DapAnDung().equals(q.getCH_DapAn2())) {
                dapanChar = "B";
            } else if (q.getDA_DapAnDung().equals(q.getCH_DapAn3())) {
                dapanChar = "C";
            } else if (q.getDA_DapAnDung().equals(q.getCH_DapAn4())) {
                dapanChar = "D";
            }

            DefaultTableModel model = (DefaultTableModel) jtable_Cauhoi.getModel();
            model.addRow(new Object[]{q.getCH_Id(), q.getHP_Id(), q.getCH_CauHoi(), q.getCH_DapAn1(), q.getCH_DapAn2(), q.getCH_DapAn3(), q.getCH_DapAn4(), dapanChar, q.getMD_TenMucDo()});
        }
        jtable_Cauhoi.getColumnModel().getColumn(0).setPreferredWidth(35);
        jtable_Cauhoi.getColumnModel().getColumn(3).setPreferredWidth(35);
        jtable_Cauhoi.getColumnModel().getColumn(4).setPreferredWidth(35);
        jtable_Cauhoi.getColumnModel().getColumn(5).setPreferredWidth(35);
        jtable_Cauhoi.getColumnModel().getColumn(6).setPreferredWidth(35);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new java.awt.Label();
        tillte = new java.awt.Label();
        btnMinSreen = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        Cauhoi = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_Cauhoi = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        input_CauHoi = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        input_A = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        btn_insert = new java.awt.Button();
        btn_cancel = new java.awt.Button();
        mess = new java.awt.Label();
        Input_C = new javax.swing.JLabel();
        input_C = new java.awt.TextField();
        Input_D = new javax.swing.JLabel();
        input_D = new java.awt.TextField();
        input_B = new java.awt.TextField();
        Input_B = new javax.swing.JLabel();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        Dapandung = new java.awt.Choice();
        MucDo = new java.awt.Choice();
        label6 = new java.awt.Label();
        HocPhan = new java.awt.Choice();
        Input_D1 = new javax.swing.JLabel();
        input_id = new java.awt.TextField();
        label1 = new java.awt.Label();
        choice_mahocphan = new java.awt.Choice();
        button1 = new java.awt.Button();
        choice_dokho = new java.awt.Choice();
        button2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(41, 47, 54));
        jPanel1.setForeground(new java.awt.Color(41, 47, 54));

        btnClose.setAlignment(java.awt.Label.CENTER);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("X");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        tillte.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tillte.setForeground(new java.awt.Color(255, 255, 255));
        tillte.setText("HOME");

        btnMinSreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinSreen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMinSreen.setForeground(new java.awt.Color(255, 255, 255));
        btnMinSreen.setText("_");
        btnMinSreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinSreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tillte, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(803, 803, 803)
                .addComponent(btnMinSreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tillte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinSreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("Học Phần");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Cauhoi.setText("Câu Hỏi");
        Cauhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CauhoiActionPerformed(evt);
            }
        });

        jButton3.setText("Tạo Đề");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setEnabled(false);

        jtable_Cauhoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO.", "Mã học phần", "Câu hỏi", " A", "B", "C", "D", "Đáp án đúng", "Mức độ", "Tác vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable_Cauhoi.setColumnSelectionAllowed(true);
        jtable_Cauhoi.setRowHeight(40);
        jtable_Cauhoi.setSelectionBackground(new java.awt.Color(144, 175, 195));
        jtable_Cauhoi.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtable_Cauhoi);
        jtable_Cauhoi.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel1.setText("Câu hỏi");

        jLabel5.setText("A");

        btn_insert.setLabel("Thêm");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_cancel.setLabel("Huỷ");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        Input_C.setText("C");

        input_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_CActionPerformed(evt);
            }
        });

        Input_D.setText("D");

        input_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_DActionPerformed(evt);
            }
        });

        Input_B.setText("B");

        label4.setText("Mức độ");

        label5.setText("Đáp án đúng");

        label6.setText("Học phần");

        Input_D1.setText("No.");

        input_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(input_CauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(input_A, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40)
                                            .addComponent(Input_B, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(input_C, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Input_D, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(input_D, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(input_B, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Dapandung, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(input_id, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MucDo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(Input_C, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(357, 357, 357))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_CauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(input_B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Input_B, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Input_C)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(input_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)))
                            .addComponent(Input_D)
                            .addComponent(input_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Dapandung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MucDo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Input_D1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Danh Mục Câu Hỏi");

        choice_mahocphan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        choice_mahocphan.setFocusable(false);
        choice_mahocphan.setName(""); // NOI18N

        button1.setLabel("Tìm kiếm");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("Mức Độ");
        button2.setMinimumSize(new java.awt.Dimension(64, 24));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cauhoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(choice_dokho, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(choice_mahocphan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(Cauhoi)
                        .addComponent(jButton3))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(choice_mahocphan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choice_dokho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMinSreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinSreenMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinSreenMouseClicked

    private void CauhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CauhoiActionPerformed

    }//GEN-LAST:event_CauhoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Home hjframe = new Home(GV_Ten, GV_ID);
        hjframe.setVisible(true);
        hjframe.pack();
        hjframe.setLocationRelativeTo(null);
        hjframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        choice_dokho.select("Độ Khó(Tất cả)");
        String gettimkiem = choice_mahocphan.getSelectedItem();
        DefaultTableModel obj = (DefaultTableModel) jtable_Cauhoi.getModel();
        TableRowSorter<DefaultTableModel> objl = new TableRowSorter<>(obj);
        jtable_Cauhoi.setRowSorter(objl);
        if (gettimkiem.equals("Học Phần(Tất cả)")) {
            gettimkiem = "";
            objl.setRowFilter(RowFilter.regexFilter(gettimkiem));
        } else {
            objl.setRowFilter(RowFilter.regexFilter(gettimkiem));

        }
//        if (gettimkiem.equals("Học Phần(Tất cả)")) {
//            gettimkiem = "";
//            objl.setRowFilter(RowFilter.regexFilter(gettimkiem));
//        } else {
//            objl.setRowFilter(RowFilter.regexFilter(gettimkiem));
//        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        choice_mahocphan.select("Học Phần(Tất cả)");
        String getmucdo = choice_dokho.getSelectedItem();
        DefaultTableModel obj2 = (DefaultTableModel) jtable_Cauhoi.getModel();
        TableRowSorter<DefaultTableModel> objl2 = new TableRowSorter<>(obj2);
        jtable_Cauhoi.setRowSorter(objl2);
        if (getmucdo.equals("Độ Khó(Tất cả)")) {
            getmucdo = "";
            objl2.setRowFilter(RowFilter.regexFilter(getmucdo));
        } else {
            objl2.setRowFilter(RowFilter.regexFilter(getmucdo));

        }
    }//GEN-LAST:event_button2ActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        //         jmess.setVisible();
    }//GEN-LAST:event_btn_cancelActionPerformed

    public static int maxCH_IDMYSQL() {
        int a = 0;
        String maxCH = "select max(CH_Id) as id from cau_hoi;";
        PreparedStatement stm;
        try {
            stm = MySQLConnect.MySQLConnect().prepareStatement(maxCH);
            ResultSet rs = stm.executeQuery();
            if (rs.next()) {
                a = rs.getInt("id");
            }

        } catch (SQLException ex) {
            Logger.getLogger(jcauhoi.class.getName()).log(Level.SEVERE, null, ex);
        }
        return a + 1;
    }

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        String getCauHoi = input_CauHoi.getText();
        String getCauHoiID = input_id.getText();
        String getA = input_A.getText();
        String getB = input_B.getText();
        String getC = input_C.getText();
        String getD = input_D.getText();
        String getDapAnDung = switch (Dapandung.getSelectedItem()) {
            case "A" ->
                getA;
            case "B" ->
                getB;
            case "C" ->
                getC;
            default ->
                getD;
        };
        String getMaHocPhan = HocPhan.getSelectedItem();
        String getMucDo = switch (MucDo.getSelectedItem()) {
            case "De" ->
                "D";
            case "Trung Binh" ->
                "T";
            default ->
                "K";
        };
        String insertCauHoi = "INSERT INTO `cau_hoi`(`CH_Id`, `HP_Id`, `MD_Id`, `CH_CauHoi`, `CH_DapAn1`, `CH_DapAn2`, `CH_DapAn3`, `CH_DapAn4`, `DA_DapAnDung`) "
                + "VALUES ('" + getCauHoiID + "','" + getMaHocPhan + "','" + getMucDo + "','" + getCauHoi + "','" + getA + "','" + getB + "','" + getC + "','" + getD + "','" + getDapAnDung + "') ";
        System.out.println(insertCauHoi);
        Statement stm;
        try {
            stm = MySQLConnect.MySQLConnect().createStatement();
            stm.execute(insertCauHoi);

            JOptionPane.showMessageDialog(null, "Đã thêm thành công!");

            this.dispose();
            new jcauhoi(GV_ID, GV_Ten).setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(jcauhoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_insertActionPerformed

    private void input_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_CActionPerformed

    private void input_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_DActionPerformed

    private void input_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_idActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                TaoDeThi tdt = new TaoDeThi(GV_ID, GV_Ten);
        tdt.setVisible(true);
        tdt.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jcauhoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jcauhoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jcauhoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jcauhoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new jcauhoi(0, "").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cauhoi;
    private java.awt.Choice Dapandung;
    private java.awt.Choice HocPhan;
    private javax.swing.JLabel Input_B;
    private javax.swing.JLabel Input_C;
    private javax.swing.JLabel Input_D;
    private javax.swing.JLabel Input_D1;
    private java.awt.Choice MucDo;
    private java.awt.Label btnClose;
    private java.awt.Label btnMinSreen;
    private java.awt.Button btn_cancel;
    private java.awt.Button btn_insert;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Choice choice_dokho;
    private java.awt.Choice choice_mahocphan;
    private java.awt.TextField input_A;
    private java.awt.TextField input_B;
    private java.awt.TextField input_C;
    private java.awt.TextField input_CauHoi;
    private java.awt.TextField input_D;
    private java.awt.TextField input_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable_Cauhoi;
    private java.awt.Label label1;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label mess;
    private java.awt.Label tillte;
    // End of variables declaration//GEN-END:variables
}
