/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MultipleChoiceCode;

import CauHoi.LoadQuestions;
import CauHoi.Questions;
import java.awt.Choice;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class TaoDeThi extends javax.swing.JFrame {

    int GV_Id;
    String GV_Ten;
    int DT_SoCau;
    ArrayList<Questions> randomcauhoi = new ArrayList<>();

    /**
     * Creates new form TaoDeThi
     *
     * @param GetId
     * @param GetTen
     */
    public TaoDeThi(int GetId, String GetTen) {
        initComponents();
        this.setLocationRelativeTo(null);
        GV_Id = GetId;
        GV_Ten = GetTen;
        showChoiceHocPhan(choiceHocPhan, false);
        showDethi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        btnClose2 = new java.awt.Label();
        btnMinSreen2 = new java.awt.Label();
        edit = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        MucDo = new java.awt.Choice();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        A = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        CauHoi = new javax.swing.JTextField();
        Dapandung = new java.awt.Choice();
        Edit = new java.awt.Button();
        Huy = new java.awt.Button();
        label6 = new java.awt.Label();
        B = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        C = new javax.swing.JTextField();
        label8 = new java.awt.Label();
        D = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnClose3 = new java.awt.Label();
        btnMinSreen3 = new java.awt.Label();
        edit1 = new java.awt.Label();
        jPanel6 = new javax.swing.JPanel();
        choiceHocPhan = new java.awt.Choice();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        input_tendethi = new javax.swing.JTextField();
        label12 = new java.awt.Label();
        input_MD_de = new javax.swing.JTextField();
        AddDeThi = new java.awt.Button();
        Huy1 = new java.awt.Button();
        label13 = new java.awt.Label();
        input_slthisinh = new javax.swing.JTextField();
        label14 = new java.awt.Label();
        input_socau = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label15 = new java.awt.Label();
        input_matkhau = new javax.swing.JTextField();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        input_MD_kho = new javax.swing.JTextField();
        input_madethi = new javax.swing.JTextField();
        label19 = new java.awt.Label();
        input_MD_trungbinh = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        HocPhan = new javax.swing.JButton();
        Cauhoi = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        input_Thoigian = new javax.swing.JTextField();
        label20 = new java.awt.Label();
        mess = new java.awt.Label();
        btn_random = new java.awt.Button();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(41, 47, 54));
        jPanel3.setForeground(new java.awt.Color(41, 47, 54));

        btnClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnClose2.setForeground(new java.awt.Color(255, 255, 255));
        btnClose2.setText("X");
        btnClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClose2MouseClicked(evt);
            }
        });

        btnMinSreen2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinSreen2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMinSreen2.setForeground(new java.awt.Color(255, 255, 255));
        btnMinSreen2.setText("_");
        btnMinSreen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinSreen2MouseClicked(evt);
            }
        });

        edit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Sửa Thông Tin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinSreen2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnMinSreen2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(198, 197, 185));

        label2.setText("Câu hỏi");

        label3.setText("A.");

        label4.setText("Mức độ");

        label5.setText("Đáp án đúng");

        CauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CauHoiActionPerformed(evt);
            }
        });

        Edit.setLabel("Sửa");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Huy.setLabel("Huỷ");
        Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyActionPerformed(evt);
            }
        });

        label6.setText("B.");

        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        label7.setText("C.");

        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        label8.setText("D.");

        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CauHoi))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(A))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(B))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(C))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(D))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Dapandung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(MucDo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dapandung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MucDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Huy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(41, 47, 54));
        jPanel5.setForeground(new java.awt.Color(41, 47, 54));

        btnClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnClose3.setForeground(new java.awt.Color(255, 255, 255));
        btnClose3.setText("X");
        btnClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClose3MouseClicked(evt);
            }
        });

        btnMinSreen3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinSreen3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMinSreen3.setForeground(new java.awt.Color(255, 255, 255));
        btnMinSreen3.setText("_");
        btnMinSreen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinSreen3MouseClicked(evt);
            }
        });

        edit1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        edit1.setForeground(new java.awt.Color(255, 255, 255));
        edit1.setText("Tạo Đề Thi");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinSreen3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnMinSreen3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(198, 197, 185));

        label9.setText("Mã đề thi");

        label10.setText("Tên đề thi");

        label11.setText("Thời gian thi");

        label12.setText("Giới hạn thí sinh");
        label12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label12MouseClicked(evt);
            }
        });

        input_MD_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_MD_deActionPerformed(evt);
            }
        });

        AddDeThi.setLabel("Thêm");
        AddDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDeThiActionPerformed(evt);
            }
        });

        Huy1.setLabel("Huỷ");
        Huy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Huy1ActionPerformed(evt);
            }
        });

        label13.setText("Học phần");

        input_slthisinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_slthisinhActionPerformed(evt);
            }
        });

        label14.setText("Số câu");
        label14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label14MouseClicked(evt);
            }
        });

        input_socau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_socauActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Tên đề thi", "Học phần", "Số lượng thí sinh", "Thời gian thi", "Mật khẩu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        label15.setText("Mật khẩu");
        label15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label15MouseClicked(evt);
            }
        });

        input_matkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_matkhauActionPerformed(evt);
            }
        });

        label16.setText("Mức độ");

        label17.setText("Dễ");

        label18.setText("Trung bình");

        input_MD_kho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_MD_khoActionPerformed(evt);
            }
        });

        input_madethi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_madethiActionPerformed(evt);
            }
        });

        label19.setText("Khó");

        input_MD_trungbinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_MD_trungbinhActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Danh Mục Đề Thi");

        HocPhan.setText("Học Phần");
        HocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HocPhanActionPerformed(evt);
            }
        });

        Cauhoi.setText("Câu Hỏi");
        Cauhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CauhoiActionPerformed(evt);
            }
        });

        jButton3.setText("Tạo Đề");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        input_Thoigian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_ThoigianActionPerformed(evt);
            }
        });

        label20.setText("Phút");
        label20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label20MouseClicked(evt);
            }
        });

        mess.setAlignment(java.awt.Label.CENTER);

        btn_random.setLabel("Ngẫu nhiên");
        btn_random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_randomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(HocPhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cauhoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(input_socau, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(input_slthisinh)
                                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(input_tendethi)
                                    .addComponent(input_madethi)
                                    .addComponent(choiceHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(input_Thoigian, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                    .addGap(101, 101, 101)
                                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(input_MD_trungbinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(input_MD_kho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(input_MD_de, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_random, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(input_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(Huy1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(AddDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HocPhan)
                        .addComponent(Cauhoi)
                        .addComponent(jButton3))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(input_madethi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(input_tendethi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(choiceHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(input_slthisinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(input_Thoigian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_socau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(input_MD_de, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(input_MD_trungbinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btn_random, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_MD_kho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddDeThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Huy1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showDethi() {
        String dethi = "select * from de_thi dt join hoc_phan hp on dt.HP_Id = hp.HP_Id where GV_Id = ?";
        try {
            PreparedStatement stm = MySQLConnect.MySQLConnect().prepareStatement(dethi);
            stm.setInt(1, GV_Id);
            ResultSet rs = stm.executeQuery();
            while (rs.next()) {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{rs.getInt("DT_Id"), rs.getString("DT_TenDeThi"), rs.getString("HP_Id"), rs.getString("DT_SoLuongThiSinh"), rs.getTime("DT_ThoiGian"), rs.getInt("DT_MatKhau")});
            }
        } catch (Exception e) {
        }
    }

    private void btnClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClose2MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnClose2MouseClicked

    private void btnMinSreen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinSreen2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinSreen2MouseClicked

    private void CauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CauHoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CauHoiActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed

    }//GEN-LAST:event_EditActionPerformed

    private void HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyActionPerformed

    }//GEN-LAST:event_HuyActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DActionPerformed

    private void btnClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClose3MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnClose3MouseClicked

    private void btnMinSreen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinSreen3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinSreen3MouseClicked

    private void input_MD_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_MD_deActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_MD_deActionPerformed

    public void insert_cauhoi(int de, int trungbinh, int kho) {
        LoadQuestions load = new LoadQuestions(GV_Id);
        ArrayList<Questions> list = load.loadQuestions(GV_Id);
        ArrayList<String> mucdode = new ArrayList<>();
        ArrayList<String> mucdotrungbinh = new ArrayList<>();
        ArrayList<String> mucdokho = new ArrayList<>();

        ArrayList<Questions> list_cau_hoi_de = new ArrayList<>();
        ArrayList<Questions> list_cau_hoi_trungbinh = new ArrayList<>();
        ArrayList<Questions> list_cau_hoi_kho = new ArrayList<>();

        for (Questions questions : list) {
            switch (questions.getMD_TenMucDo()) {
                case "De":
                    Questions qstDeadd = new Questions(questions.getCH_Id(), questions.getHP_Id(), questions.getMD_TenMucDo(), questions.getCH_CauHoi(),
                            questions.getCH_DapAn1(), questions.getCH_DapAn2(), questions.getCH_DapAn3(), questions.getCH_DapAn4(), questions.getDA_DapAnDung());
                    list_cau_hoi_de.add(qstDeadd);
                    break;
                case "Trung Binh":
                    Questions qstTBadd = new Questions(questions.getCH_Id(), questions.getHP_Id(), questions.getMD_TenMucDo(), questions.getCH_CauHoi(),
                            questions.getCH_DapAn1(), questions.getCH_DapAn2(), questions.getCH_DapAn3(), questions.getCH_DapAn4(), questions.getDA_DapAnDung());
                    list_cau_hoi_trungbinh.add(qstTBadd);
                    break;
                default:
                    Questions qstKadd = new Questions(questions.getCH_Id(), questions.getHP_Id(), questions.getMD_TenMucDo(), questions.getCH_CauHoi(),
                            questions.getCH_DapAn1(), questions.getCH_DapAn2(), questions.getCH_DapAn3(), questions.getCH_DapAn4(), questions.getDA_DapAnDung());
                    list_cau_hoi_kho.add(qstKadd);
                    break;
            }
        }
        randomcauhoi = show_random_i_cauhoi(list_cau_hoi_de, list_cau_hoi_trungbinh, list_cau_hoi_kho, de, trungbinh, kho);
    }

    public void showChoiceHocPhan(Choice a, boolean all) {
        if (all) {
            a.add("Học Phần(Tất cả)");
        }
        String timkiem = "SELECT * FROM `hoc_phan` WHERE GV_Id = ?;";
        try {
            PreparedStatement stm = MySQLConnect.MySQLConnect().prepareStatement(timkiem);
            stm.setInt(1, GV_Id);
            ResultSet rs = stm.executeQuery();
            while (rs.next()) {
                a.add(rs.getString("HP_Id"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(jcauhoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static ArrayList<Integer> randomMucDoCauHoi(int DT_SoCau) {

        Random rand = new Random();
        int a, b, c;
        ArrayList<Integer> tong = new ArrayList<>();
        while (true) {
            a = rand.nextInt(0, DT_SoCau);
            b = rand.nextInt(0, DT_SoCau);
            c = rand.nextInt(0, DT_SoCau);
            if (a + b + c == DT_SoCau && c < a && c < b && b < a) {
                tong.add(0, a);
                tong.add(1, b);
                tong.add(2, c);
                return tong;
            }
        }
    }

    private void AddDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDeThiActionPerformed
        ArrayList<Integer> DT_SoCauTheoMucDo = new ArrayList<>();
        int DT_Id = Integer.parseInt(input_madethi.getText());
        String DT_TenDeThi = input_tendethi.getText();
        String DT_MatKhau = input_matkhau.getText();
        String HP_Id = choiceHocPhan.getSelectedItem();
        DT_SoCau = Integer.parseInt(input_socau.getText());
        int DT_SoLuongThiSinh = Integer.parseInt(input_slthisinh.getText());
        int DT_ThoiGianThi = Integer.parseInt(input_Thoigian.getText());
        ArrayList<Integer> getTong3so = new ArrayList<>();
        getTong3so = randomMucDoCauHoi(DT_SoCau);
        if (input_MD_de.getText().equals("") && input_MD_kho.getText().equals("") && input_MD_trungbinh.getText().equals("")) {
            for (int i = 0; i < getTong3so.size(); i++) {
                DT_SoCauTheoMucDo.add(i, getTong3so.get(i));
            }
        } else {
            DT_SoCauTheoMucDo.add(0, Integer.valueOf(input_MD_de.getText()));
            DT_SoCauTheoMucDo.add(1, Integer.valueOf(input_MD_trungbinh.getText()));
            DT_SoCauTheoMucDo.add(2, Integer.valueOf(input_MD_kho.getText()));
        }

        if (DT_SoCauTheoMucDo.get(0) + DT_SoCauTheoMucDo.get(1) + DT_SoCauTheoMucDo.get(2) != DT_SoCau) {
            mess.setText("Tổng 3 mức độ không hợp lệ");
            mess.setForeground(Color.red);
        } else {
            try {
                String checkDeThi = "select DT_Id from De_thi where DT_Id = '" + DT_Id + "'";
                PreparedStatement stm_check = MySQLConnect.MySQLConnect().prepareStatement(checkDeThi);
                ResultSet rs = stm_check.executeQuery();
                if (rs.next()) {
                    mess.setText(DT_Id + " đã tồn tại");
                    mess.setForeground(Color.red);
                } else {

                    insert_cauhoi(DT_SoCauTheoMucDo.get(0), DT_SoCauTheoMucDo.get(1), DT_SoCauTheoMucDo.get(2));

                    String insert_dethi = "INSERT INTO `de_thi` (`DT_Id`, `DT_TenDeThi`, `DT_MatKhau`, `HP_Id`, `DT_SoLuongThiSinh`, `DT_ThoiGian`, `DT_SoCau`) VALUES (?,?,?,?,?,TIME_FORMAT(SEC_TO_TIME(?* 60), '%H:%i:%s'),?);";

                    PreparedStatement stm = MySQLConnect.MySQLConnect().prepareStatement(insert_dethi);
                    stm.setInt(1, DT_Id);
                    stm.setString(2, DT_TenDeThi);
                    stm.setString(3, DT_MatKhau);
                    stm.setString(4, HP_Id);
                    stm.setInt(5, DT_SoLuongThiSinh);
                    stm.setInt(6, DT_ThoiGianThi);
                    stm.setInt(7, DT_SoCau);
                    stm.execute();

                    String insert_chitiet = "insert into chi_tiet_de_thi values(?,?);";
                    
                    for (Questions questions : randomcauhoi) {
                        int CH_Id = questions.getCH_Id();
                        PreparedStatement stmcauhoi = MySQLConnect.MySQLConnect().prepareStatement(insert_chitiet);
                        stmcauhoi.setInt(1, CH_Id);
                        stmcauhoi.setInt(2, DT_Id);
                        stmcauhoi.execute();
                        stmcauhoi.close();
                    }
                    
//                đối tương array lưu các học sinh có trong Học phần 
                    ArrayList<String> ms_hs = new ArrayList<>();
//              Lấy những học sinh đang học học phần tại lớp đó.
                    String get_hs = "SELECT HS_Id FROM chi_tiet_giang_day ct join lop l on ct.LOP_Id = l.LOP_Id join hoc_phan hp on ct.HP_Id = hp.HP_Id join de_thi dt on dt.HP_Id= hp.HP_Id where ct.HP_Id=? and hp.GV_Id=? and DT_Id = ?;";

                    PreparedStatement stm_get_hs = MySQLConnect.MySQLConnect().prepareStatement(get_hs);
                    stm_get_hs.setString(1, HP_Id);
                    stm_get_hs.setInt(2, GV_Id);
                    stm_get_hs.setInt(3, DT_Id);
                    ResultSet rs_get_hs = stm_get_hs.executeQuery();
                    while (rs_get_hs.next()) {
                        ms_hs.add(rs_get_hs.getString("HS_Id"));
                    }
                    stm_get_hs.close();
                    //                1.? hocsinh 2.? de thi 3.? tinhtrang    
                    for (String ms_h : ms_hs) {
                        String insert_trangthai = "insert into trang_thai values(?,?,?)";
                        PreparedStatement stm_insert_trangthai = MySQLConnect.MySQLConnect().prepareStatement(insert_trangthai);
                        stm_insert_trangthai.setString(1, ms_h);
                        stm_insert_trangthai.setInt(2, DT_Id);
                        stm_insert_trangthai.setInt(3, 0);
                        stm_insert_trangthai.execute();
                        stm_insert_trangthai.close();
                    }

                    JOptionPane.showMessageDialog(null, "Đã thêm thành công!");
                    this.dispose();
                    new TaoDeThi(GV_Id, GV_Ten).setVisible(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(jcauhoi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_AddDeThiActionPerformed

    public static ArrayList<Questions> show_random_i_cauhoi(ArrayList<Questions> list_cau_hoi_de, ArrayList<Questions> list_cau_hoi_trungbinh, ArrayList<Questions> list_cau_hoi_kho, int de, int trungbinh, int kho) {

        Collections.shuffle(list_cau_hoi_de);
        Collections.shuffle(list_cau_hoi_trungbinh);
        Collections.shuffle(list_cau_hoi_kho);

        ArrayList<Questions> list_cau_hoi_da_tron_mucdo = new ArrayList<>();
        for (int i = 0; i < de; i++) {
            Questions a = list_cau_hoi_de.get(i);
            list_cau_hoi_da_tron_mucdo.add(a);
        }

        for (int i = 0; i < trungbinh; i++) {
            Questions b = list_cau_hoi_trungbinh.get(i);
            list_cau_hoi_da_tron_mucdo.add(b);
        }

        if (kho != 0) {
            for (int i = 0; i < kho; i++) {
                Questions b = list_cau_hoi_kho.get(i);
                list_cau_hoi_da_tron_mucdo.add(b);
            }
        }
        Collections.shuffle(list_cau_hoi_da_tron_mucdo);

        return list_cau_hoi_da_tron_mucdo;
    }

    private void Huy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Huy1ActionPerformed
        for (Questions q : randomcauhoi) {
            System.out.println(q.toString());
        }
    }//GEN-LAST:event_Huy1ActionPerformed

    private void label12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label12MouseClicked

    private void input_slthisinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_slthisinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_slthisinhActionPerformed

    private void label14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label14MouseClicked

    private void input_socauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_socauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_socauActionPerformed

    private void label15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label15MouseClicked

    private void input_matkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_matkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_matkhauActionPerformed

    private void input_MD_khoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_MD_khoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_MD_khoActionPerformed

    private void input_madethiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_madethiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_madethiActionPerformed

    private void input_MD_trungbinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_MD_trungbinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_MD_trungbinhActionPerformed

    private void CauhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CauhoiActionPerformed
        jcauhoi jch = new jcauhoi(GV_Id, GV_Ten);
        jch.setVisible(true);
        jch.pack();
        jch.setLocationRelativeTo(null);
        jch.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_CauhoiActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TaoDeThi tdt = new TaoDeThi(GV_Id, GV_Ten);
        tdt.setVisible(true);
        tdt.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void HocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HocPhanActionPerformed
        Home hjframe = new Home(GV_Ten, GV_Id);
        hjframe.setVisible(true);
        hjframe.pack();
        hjframe.setLocationRelativeTo(null);
        hjframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_HocPhanActionPerformed

    private void input_ThoigianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_ThoigianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_ThoigianActionPerformed

    private void label20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label20MouseClicked

    private void btn_randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_randomActionPerformed

        DT_SoCau = Integer.parseInt(input_socau.getText());
        ArrayList<Integer> setNgauNhien = new ArrayList<>();
        setNgauNhien = randomMucDoCauHoi(DT_SoCau);
        input_MD_de.setText(Integer.toString(setNgauNhien.get(0)));
        input_MD_trungbinh.setText(Integer.toString(setNgauNhien.get(1)));
        input_MD_kho.setText(Integer.toString(setNgauNhien.get(2)));
    }//GEN-LAST:event_btn_randomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoDeThi(0, "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private java.awt.Button AddDeThi;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private javax.swing.JTextField CauHoi;
    private javax.swing.JButton Cauhoi;
    private javax.swing.JTextField D;
    private java.awt.Choice Dapandung;
    private java.awt.Button Edit;
    private javax.swing.JButton HocPhan;
    private java.awt.Button Huy;
    private java.awt.Button Huy1;
    private java.awt.Choice MucDo;
    private java.awt.Label btnClose2;
    private java.awt.Label btnClose3;
    private java.awt.Label btnMinSreen2;
    private java.awt.Label btnMinSreen3;
    private java.awt.Button btn_random;
    private java.awt.Choice choiceHocPhan;
    private java.awt.Label edit;
    private java.awt.Label edit1;
    private javax.swing.JTextField input_MD_de;
    private javax.swing.JTextField input_MD_kho;
    private javax.swing.JTextField input_MD_trungbinh;
    private javax.swing.JTextField input_Thoigian;
    private javax.swing.JTextField input_madethi;
    private javax.swing.JTextField input_matkhau;
    private javax.swing.JTextField input_slthisinh;
    private javax.swing.JTextField input_socau;
    private javax.swing.JTextField input_tendethi;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Label mess;
    // End of variables declaration//GEN-END:variables

    private int setNgauNhien(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
